### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by buiguesj** [ZhijianZhou01/VirusRecom#2]
Hi!!
I'm struggling in using the tool Virusrecom. First of all, I tried to execute the code pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple on the Github cloned repository, but seems that https://pypi.tuna.tsinghua.edu.cn/simple is not working, this is what I got:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f29988995e0>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido')': /simple/matplotlib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2998899910>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido')': /simple/matplotlib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2998889610>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido')': /simple/matplotlib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2998889910>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido')': /simple/matplotlib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f29988894f0>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido')': /simple/matplotlib/
ERROR: Could not find a version that satisfies the requirement matplotlib==2.2.5 (from versions: none)
ERROR: No matching distribution found for matplotlib==2.2.5
WARNING: There was an error checking the latest version of pip.

*Pip version 22.2.2

After no success in installing the requirments through pip...requirements.txt; I downloaded the program directly from the releases site. This is the code that I used:

./virusrecom -a /home/nucleotides_spike/nuc_spike_alignment.fasta -q VirEvo_BatCoV_spike -l /home/nucleotides_spike/lineages.txt -g n -m p -w 100 -s 20  -o /home/nucleotides_spike/outdir_recomb_alphacov -at clustalo

And I got the following issue.

/home/jaimeb/VirusRecomb/main/my_func.py:568: UserWarning: Tight layout not applied. tight_layout cannot make axes height small enough to accommodate all axes decorations
    VirusRecom starts scanning using sliding window ...

Traceback (most recent call last):
  File "main.py", line 553, in <module>
  File "corecp.py", line 144, in virus_infor_calculate
  File "my_func.py", line 668, in mwic_plot
  File "matplotlib/pyplot.py", line 729, in savefig
  File "matplotlib/figure.py", line 2180, in savefig
  File "matplotlib/backend_bases.py", line 2091, in print_figure
  File "matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
  File "matplotlib/artist.py", line 38, in draw_wrapper
  File "matplotlib/figure.py", line 1709, in draw
  File "matplotlib/image.py", line 135, in _draw_list_compositing_images
  File "matplotlib/artist.py", line 38, in draw_wrapper
  File "matplotlib/axes/_base.py", line 2647, in draw
  File "matplotlib/image.py", line 135, in _draw_list_compositing_images
  File "matplotlib/artist.py", line 38, in draw_wrapper
  File "matplotlib/lines.py", line 783, in draw
  File "matplotlib/colors.py", line 177, in to_rgba
  File "matplotlib/colors.py", line 233, in _to_rgba_no_colorcycle
ValueError: Invalid RGBA argument: 'sage'
[11040] Failed to execute script main

Thank you in advance! Seems a great tool!

**Comment by ZhijianZhou01** [comment]
My suggestion is to fully read the manual repeatedly, such as "-a" means that the input-sequence-data has been aligned. Alternatively, you can first run the process with test data.

**Comment by ZhijianZhou01** [comment]
Besides, relevant key parameters need to be adjusted according to the actual situations (such as lineage data or un-lineage data, genome length etc), such as -w, -s, -cp, etc. 
No thanks.

**Comment by ZhijianZhou01** [comment]
virusrecom now supports online installation, please use the following command:

pip install virusrecom
