### ISSUE TITLE
A bug non-lineage data analysis

### ISSUE THREAD

**Issue by Wesady** [ZhijianZhou01/VirusRecom#4]
When run `virusrecom -a alns.fasta -q HNU1-1 -l alns_seq_taxon.txt -g n -m a -w 800 -s 100 -cp 0.7 -mr 6000 -le r -o output
`, the HNU1-1_site_WIC_from_lineages.pdf is blank

**Comment by Wesady** [comment]
sorry, it's just that the file is so big that it takes a long time to open.

**Comment by ZhijianZhou01** [comment]
Thank you for your feedback. All the features of virusrecom can run normally on several test computers (from pip or binary files). Therefore, there will be no obvious bugs in most cases.

**Comment by ZhijianZhou01** [comment]
In addition, the original matrix data of all graphics are provided in the output directory  , which can be easily used for manual redrawing.


Sincerely,

Zhi-Jian Zhou

**Comment by liamxg** [comment]
@ZhijianZhou01 ,

Can i add your wechat?
